### ISSUE TITLE
Cannot build with ant

### ISSUE THREAD

**Issue by EliHei** [roettig/NRPSpredictor2#2]
Trying to run the shell script on both MacOS and Linux, I get the following error. Do you have any idea why?

`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at org.roettig.NRPSpredictor2.NRPSpredictor2.<clinit>(NRPSpredictor2.java:51)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more`

**Comment by kblin** [comment]
I think I've seen that one before. It's caused by using the wrong version of the LogManager API. That said, I'm afraid I don't remember if I managed to fix it somehow or if I just went back to running the .jar file we shipped with antiSMASH.

**Comment by EliHei** [comment]
@kblin 
So much thanks! 
How can I fix it?

**Comment by kblin** [comment]
It was a bit convoluted, iirc. I had to install log4j 2, add `:lib/log4j-core-2.3.jar:lib/log4j-api-2.3.jar` to the classpath in the `NRPSPredictor.sh` script, and add a logging configuration option like so `-Dlog4j.configurationFile=file:///home/kai/dev/tools/NRPSpredictor2/src/log4j2.xml`

The config file looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
    </Console>
  </Appenders>
  <Loggers>
    <Root level="error">
      <AppenderRef ref="Console"/>
    </Root>
    <Root level="info">
      <AppenderRef ref="Console"/>
    </Root>
  </Loggers>
</Configuration>
```

That made it work for me.

**Comment by EliHei** [comment]
@kblin 
Thanks. Would you please put your `NRPSPredictor.sh` script here? Because I tried something similar but I still can not run the script.

**Comment by erfanloghmani** [comment]
@EliHei 
my `NRPSPredictor.sh` is like this:
```sh
#!/bin/bash
java -Ddatadir=data -Dlog4j.configurationFile=file:///home/erfan/NRPSpredictor2/src/log4j2.xml -cp lib/dom4j-1.6.1.jar:lib/jaxen-1.1-beta-6.jar:build/NRPSpredictor2.jar:lib/java-getopt-1.0.13.jar:lib/Utilities.jar:lib/libsvm.jar:lib/log4j-core-2.3.jar:lib/log4j-api-2.3.jar org.roettig.NRPSpredictor2.NRPSpredictor2 $*
```
Be aware that you have to change `///home/erfan/NRPSpredictor2` to your path to project directory.
I have also created a `log4j2.xml` as @kblin said for configuration in `src` directory.

But after all running this:
```sh
sh runNRPSpredictor2.sh -i examples/examples.sigs -s 1 -r report
```

I will have new exception:
```
22:19:18.590 [main] ERROR org.roettig.NRPSpredictor2.NRPSpredictor2 - null
java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434) ~[?:1.8.0_11]
	at java.util.Properties.load0(Properties.java:353) ~[?:1.8.0_11]
	at java.util.Properties.load(Properties.java:341) ~[?:1.8.0_11]
	at org.roettig.NRPSpredictor2.NRPSpredictor2.fillPrecs(NRPSpredictor2.java:804) ~[NRPSpredictor2.jar:?]
	at org.roettig.NRPSpredictor2.NRPSpredictor2.init(NRPSpredictor2.java:184) ~[NRPSpredictor2.jar:?]
	at org.roettig.NRPSpredictor2.NRPSpredictor2.main(NRPSpredictor2.java:127) [NRPSpredictor2.jar:?]
```
@kblin Do you have any idea on this?

**Comment by roettig** [comment]
Within feature branch *Feature/mavenizing* I created a Apache  Maven  based version of NRPSPredictor2, which will build a fat jar when issuing *mvn package* that contains all dependent jars. This is more easy to handle. I also switched from *log4j2* to *slf4j* and *log4j1* impl with a property file on classpath, so no need to supply a *log4j2.xml* upon launch.

Fat jar on windows works fine for me locally using the bat script.

**Comment by EliHei** [comment]
@roettig 
Thank you for your update but I still get an Error:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project org.roettig.NRPSPredictor2: There are test failures.
[ERROR] 
[ERROR] Please refer to /s/damavand/f/asharifi/EliHei/NRPSpredictor2/NRPSpredictor2/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Comment by roettig** [comment]
What does /s/damavand/f/asharifi/EliHei/NRPSpredictor2/NRPSpredictor2/target/surefire-reports say ?
There are some test failing, which ones ?
I assume you're on a unix/macos system.

**Comment by EliHei** [comment]
@roettig 
An exception raises in test `org.roettig.NRPSpredictor2.hmmer.HMMerTest`:

`java.lang.NullPointerException
	at org.roettig.NRPSpredictor2.util.Helper.deployFile(Helper.java:53)
	at org.roettig.NRPSpredictor2.hmmer.HMMPfam.<clinit>(HMMPfam.java:38)
	at org.roettig.NRPSpredictor2.hmmer.HMMerTest.testOneFullSequence(HMMerTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.004 sec <<< FAILURE!
testOneFullSequence(org.roettig.NRPSpredictor2.hmmer.HMMerTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NullPointerException
	at org.roettig.NRPSpredictor2.util.Helper.deployFile(Helper.java:53)
	at org.roettig.NRPSpredictor2.util.Helper.deployFile(Helper.java:84)
	at org.roettig.NRPSpredictor2.hmmer.HMMerTest.testOneFullSequence(HMMerTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testTwoFullSequences(org.roettig.NRPSpredictor2.hmmer.HMMerTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException
	at org.roettig.NRPSpredictor2.util.Helper.deployFile(Helper.java:53)
	at org.roettig.NRPSpredictor2.util.Helper.deployFile(Helper.java:84)
	at org.roettig.NRPSpredictor2.hmmer.HMMerTest.testTwoFullSequences(HMMerTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.roettig.NRPSpredictor2.extraction.ADomSigExtractorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec

Results :

Tests in error: 
  testOneFullSequence(org.roettig.NRPSpredictor2.hmmer.HMMerTest)
  testTwoFullSequences(org.roettig.NRPSpredictor2.hmmer.HMMerTest)

Tests run: 10, Failures: 0, Errors: 2, Skipped: 0`

**Comment by philthiel** [comment]
Hi Marc,

hope you're fine!

I currently try to pack the software in a docker container and have similar problems as described here. I'm using Ubuntu 14.04 and OpenJDK 1.7. The ant build works fine here. The first problem when running the software was solved by copying the following files to the created resources folder:

- NRPSpredictor2-model-qualities.properties
- NRPSpredictor1-model-qualities.properties

The second problem I was able to track down is that the hmmpfam file is not executable on the my Linux. Compilation from scratch (http://eddylab.org/software/hmmer/hmmer-2.3.2.tar.gz) and copying it into the hmmer folder leads to the problem that the "-l" flag for the logfile, which is set in HMMPfam.run() is not existing in this version of hmmpfam. I tried to copy the output to the logfile manually but it obviously expects and XML format, right?  I thought the version would match but I'm stuck here now.

Can you probably tell me which hmmpfam you used?

Best,
Philipp

**Comment by kblin** [comment]
You might want to apply the patch from https://github.com/roettig/NRPSpredictor2/blob/master/misc/hmmpfam.2-3-2.c.patch before compiling.

**Comment by philthiel** [comment]
Thank you very much, this one solved my hmmpfam problem!

On Linux, I had further problems with ant/ivy and stopped following that route.

However, I managed to get a running Maven build using your branch Feature/maveninzing. 
Maybe you're interested in my changes:

- Recompile patched hmmer package and copy hmmpfam to its src folder
- Modified pom.xml: 6c8c668

I'm not a Java expert. This solution works for me but you may want to adapt my PR to your needs.

There will be a dockerized installation soon in the KohlbacherLab GitHub repo. I'll let you know:

https://github.com/KohlbacherLab/NRPSpredictor2
